### ISSUE TITLE
Support aws_lb (Load Balancing v2)

### ISSUE THREAD

**Issue by iainelder** [jckuester/awsls#18]
I'm trying to list the v2 load balancers in my account.

The obvious command fails because the [Terraform resource type aws_lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb) isn't found.
 
```text
$ awsls aws_lb

Error: no resource type found: aws_lb
```

As a workaround I can fall back to the AWS CLI with a command like this:

```text
aws elbv2 describe-load-balancers \
--query 'LoadBalancers[].[LoadBalancerName]' \
--output text
```

Has this yet to be added, or am I missing something?

**Comment by jckuester** [comment]
Hi @iainelder, looking at the [list of supported resources](https://github.com/jckuester/awsls#supported-resources), it looks like my code generator hasn't been able to cover this resource yet. I need to look into why this is a corner case and will adapt the generator accordingly.

I will come back to you. Thanks for letting me know.

**Comment by jckuester** [comment]
Hi @iainelder, I added `aws_lb` support. Note that you can also simply use `awsls lb` (the prefix `aws_` is optional for all resources).

**Comment by iainelder** [comment]
Thanks! What do I need to do to be able to use the new funcionality.

It looks like it's available in version 0.6.0 but I can't upgrade from 0.5.1 using the installer.

```bash
$ curl -sSfL https://raw.githubusercontent.com/jckuester/awsls/master/install.sh | sh -s v0.6.0
jckuester/awsls info checking GitHub for tag 'v0.6.0'
jckuester/awsls info found version: 0.6.0 for v0.6.0/linux/amd64
$ awsls --version

version: 0.5.1
commit: c6dcafc
built at: 2020-08-26T15:03:33Z
using: go1.14.2
```

**Comment by jckuester** [comment]
Sorry, I had created the tag but not the binaries with goreleaser. You can use the installer now.

**Comment by iainelder** [comment]
Thanks, yes, it works for me now!

```text
$ awsls --version

version: 0.6.0
commit: 00a4a28
built at: 2020-11-21T19:50:29Z
using: go1.15.2

$ awsls lb

TYPE     ID                                                                      
aws_lb   arn:aws:elasticloadbalancing:eu-west-1:359253527045:loadbalancer/net/...
aws_lb   arn:aws:elasticloadbalancing:eu-west-1:359253527045:loadbalancer/net/...
aws_lb   arn:aws:elasticloadbalancing:eu-west-1:359253527045:loadbalancer/app/...
aws_lb   arn:aws:elasticloadbalancing:eu-west-1:359253527045:loadbalancer/app/...
aws_lb   arn:aws:elasticloadbalancing:eu-west-1:359253527045:loadbalancer/app/...
```
