### ISSUE TITLE
Homebrew installable?

### ISSUE THREAD

**Issue by rothgar** [jckuester/awsls#23]
I see you're already using goreleaser to create releases. Would you be open to a PR that adds a [homebrew formula](https://goreleaser.com/customization/homebrew/)?

I can send the PR but you'd need to set up another repo (e.g. `jckuester/homebrew-tap`) and your CD job would need permission to push to the repo. I see you're using travis so you may already have enough permissions.

Users could then install `awsls` with `brew install jckuester/tap/awsls` and it will stay up to date. This would work for macOS and Linux.

I would love to also add brew support to some of your other tools too because I love their simplicity but always forget to update them.

**Comment by jckuester** [comment]
Sounds great @rothgar :+1: PR(s) for this would be very welcome.

**Comment by jckuester** [comment]
Damn, release time exceeded 30m: https://github.com/jckuester/awsls/runs/1582479394?check_suite_focus=true. I probably have to go back to creating releases locally? :thinking:

**Comment by rothgar** [comment]
I don't believe that's a github actions limit. You can try adding `--timeout 60m` here https://github.com/jckuester/awsls/blob/master/.github/workflows/release.yml#L22

**Comment by jckuester** [comment]
Perfect, thanks :+1:
