### ISSUE TITLE
Feature request: Support rate limiting responses

### ISSUE THREAD

**Issue by evansgp** [jckuester/awsls#4]
Hello,

Thanks for making this neat tool available. It's useful for me because sometime I want to find all resources (across different types) that have been tagged a certain way, e.g. list everything scheduled to be deleted in a "sandbox" account.

Is it possible to support the rate limiting responses from the AWS API, perhaps with some kind of exponential back off when it retries?

I currently run into these errors very quickly:

```
Error: failed to read current state of resource: error listing tags for CodeCommit Repository (arn:aws:codecommit:ap-southeast-2:REDACTED:REDACTED: SerializationError: failed to unmarshal response error
	status code: 400, request id: 6ec308ad-23ae-4d67-9b6b-40551af6656b
caused by: UnmarshalError: failed decoding error message
	00000000  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|
00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73 73 61 67 65  |tion>.  <Message|
00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|
00000030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|
00000040  74 6c 69 6e 67 45 78 63  65 70 74 69 6f 6e 3e 0a  |tlingException>.|

caused by: invalid character '<' looking for beginning of value
Error: failed to read current state of resource: Error reading CodeCommit Repository: SerializationError: failed to unmarshal response error
	status code: 400, request id: 7c1bcf92-aecf-4366-a31b-7c9f9de3a23d
caused by: UnmarshalError: failed decoding error message
	00000000  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|
00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73 73 61 67 65  |tion>.  <Message|
00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|
00000030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|
00000040  74 6c 69 6e 67 45 78 63  65 70 74 69 6f 6e 3e 0a  |tlingException>.|

caused by: invalid character '<' looking for beginning of value
Error: failed to read current state of resource: Error reading CodeCommit Repository: ThrottlingException: Rate exceeded
	status code: 400, request id: 899e23c8-3a81-4a86-ba66-060adbfa22c1
Error: failed to read current state of resource: Error reading CodeCommit Repository: ThrottlingException: Rate exceeded
	status code: 400, request id: 5220f9b7-8c3b-4d10-91de-bd560d5e494a
Error: failed to read current state of resource: Error reading CodeCommit Repository: SerializationError: failed to unmarshal response error
	status code: 400, request id: 397a4dc1-092b-490d-914f-5dcf689d2714
caused by: UnmarshalError: failed decoding error message
	00000000  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|
00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73 73 61 67 65  |tion>.  <Message|
00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|
00000030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|
00000040  74 6c 69 6e 67 45 78 63  65 70 74 69 6f 6e 3e 0a  |tlingException>.|

caused by: invalid character '<' looking for beginning of value
Error: failed to read current state of resource: Error reading CodeCommit Repository: SerializationError: failed to unmarshal response error
	status code: 400, request id: 49e3fcfb-7655-4c12-92d3-a4451010f349
caused by: UnmarshalError: failed decoding error message
	00000000  3c 54 68 72 6f 74 74 6c  69 6e 67 45 78 63 65 70  |<ThrottlingExcep|
00000010  74 69 6f 6e 3e 0a 20 20  3c 4d 65 73 73 61 67 65  |tion>.  <Message|
00000020  3e 52 61 74 65 20 65 78  63 65 65 64 65 64 3c 2f  |>Rate exceeded</|
00000030  4d 65 73 73 61 67 65 3e  0a 3c 2f 54 68 72 6f 74  |Message>.</Throt|
00000040  74 6c 69 6e 67 45 78 63  65 70 74 69 6f 6e 3e 0a  |tlingException>.|
```

Thanks!

**Comment by jckuester** [comment]
Hi @evansgp :wave: 

Thanks for opening this issue.

> Is it possible to support the rate limiting responses from the AWS API, perhaps with some kind of exponential back off when it retries?

Yes, this is also what I am thinking of as a fix. I'll come up with a solution and let you know when I am done.

**Comment by jckuester** [comment]
Hi @evansgp, I am trying to reproduce the error to create a test for the fix. Can you please write me the exact command you ran and roughly how many resources you were listing? Did the throttling only appear for CodeCommit Repository? Also, `awsls` didn't crash/panic, right? It just printed the error and continued, I hope.

**Comment by evansgp** [comment]
Hi, I used `awsls -attributes tags -region ap-southeast-2 "aws_*"`. It didn't halt and it continued going.

I got the error on KMS, SSM Documents and S3 buckets, there are about 900 resources total (yep this account needs to be cleaned up...)

**Comment by jckuester** [comment]
> yep this account needs to be cleaned up...

Hehe, we all have this problem. That's why I built https://github.com/jckuester/awsweeper. I also have planned to create a Unix-flavored brother of `awsls` called `awsrm` - stay tuned :D

 Here is a PR fixing the throtlling problem: https://github.com/jckuester/awsls/pull/7. There might be another place where I need to handle throttling, but the current fix might already be enough.

If you want, you can already `go build` the branch of the PR and tell me if it works for you (or otherwise, wait until I will merge and release).

**Comment by evansgp** [comment]
Nice! That fixes all the rate exceeded errors for me.

I'm currently using cloud custodian and aws-nuke but keen to see what you come up with :)

**Comment by jckuester** [comment]
Great :+1: Fix is released in https://github.com/jckuester/awsls/releases/tag/v0.1.2
