### ISSUE TITLE
Used aws sso for profile

### ISSUE THREAD

**Issue by wal13400** [jckuester/awsls#41]
Hello,

Is it possible to add the aws sso option to be able to used it on the CLI.

Thank you in advance,
Best regards,
Walid

**Comment by jckuester** [comment]
Hi @wal13400,

maybe you want to have a look at this issue https://github.com/jckuester/awsls/issues/27, where someone is using `awsls` with SSO by creating a profile. Or do you need anything else?

```
[profile example]
sso_start_url = https://d-1234567890.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = 123456789012
sso_role_name = AdministratorAccess
region = eu-west-1
output = json
I run any query using the profile:
```
```
$ awsls --profiles example --regions eu-west-1 "*"
```

**Comment by wal13400** [comment]
Hi @jckuester ,

Thank you very much, I thought it was not possible but did not tried like this.

Thank you !!!
