### ISSUE TITLE
homebrew complains :unneeded is deprecated

### ISSUE THREAD

**Issue by KimMichaelJones** [jckuester/awsls#45]
$ brew doctor
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the jckuester/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jckuester/homebrew-tap/Formula/awsls.rb:6

**Comment by christonog** [comment]
Not sure how to resolve, but is there any way to get this cut to a release @jckuester? Seem to still be running into the issue. Thank you!

**Comment by jckuester** [comment]
@christonog. Did it work for you? I merged https://github.com/jckuester/homebrew-tap/pull/2, so the warning should be gone now.

**Comment by christonog** [comment]
Yes, it does work for me now. Thanks so much @jckuester!
