### ISSUE TITLE
Error:️ failed to initialize Terraform AWS provider: failed to configure provider

### ISSUE THREAD

**Issue by briandunbar** [jckuester/awsls#5]
$ ./bin/awsls --version
version: 0.1.1
commit: e0ad080
built at: 2020-06-03T18:10:21Z
using: go1.13.9

awscli works against this profile

$ aws s3 ls --profile myprofile
2020-04-27 05:46:23 a

awsls  replies with a terraform error

bdunbar@hilda:~
$ ./bin/awsls -profile myprofile -region us-east-01 aws_vpc

Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region: us-east-01

bdunbar@hilda:~
$ ./bin/awsls -profile myprofile aws_vpc

Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region: 

bdunbar@hilda:~
$ ./bin/awsls aws_vpc

Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region: 

bdunbar@hilda:~
➤

**Comment by briandunbar** [comment]
Update.

I dropped into bash (normally run fish shell) set the export variables

bdunbar@hilda:~$ env | grep AWS
AWS_PROFILE=redacted
AWS_DEFAULT_REGION=us-east-1
bdunbar@hilda:~$ 

and it works

bdunbar@hilda:~$ ./bin/awsls aws_instance | grep aws_instance | wc -l
386
bdunbar@hilda:~$

**Comment by AstroTom** [comment]
Same here

**Comment by jckuester** [comment]
Thanks for opening this issue @briandunbar. I will look into the problem.

@AstroTom you are also having trouble with fishshell?

**Comment by AstroTom** [comment]
I am using standard shell / bash.

Thanks

**Comment by nyamaste** [comment]
Same here, until I added `export AWS_DEFAULT_REGION=us-east-1` to my `~/.bashrc` I would get this error:

```
~$ awsls aws_autoscaling_group -region us-east-1

Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region:

exit status 1
```

**Comment by jckuester** [comment]
Hi @nyamaste,

thanks for describing the problem. I'll fix this behavior.

**Comment by jckuester** [comment]
Hey @nyamaste :wave: 

I just noticed that you mixed up the order, i.e., flags must become before the resource type argument. So, the command you want to use is actually:

> awsls` -region us-east-1 aws_autoscaling_group

The error message is confusing, I need to check if more than one argument was provided and then fail with a better error message than what you saw.

Let me know if it works for you.

**Comment by nyamaste** [comment]
@jckuester you are right, with region flag in the right place or region env var the error disappears. So, same behavior as `awscli`.

```
~$ env|grep AWS
AWS_DEFAULT_REGION=us-east-1
~$ unset AWS_DEFAULT_REGION
~$ env|grep AWS
~$ awsls aws_autoscaling_group

Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region:

exit status 1
~$ okta-ss-dev awsls -region us-east-1 aws_autoscaling_group

TYPE                    ID                                                                REGION      CREATED
...
```

**Comment by MorganGeek** [comment]
I would be nice if awsls could read the values from ~/.aws/credentials :-) instead of  having to expose them as environment variables.

**Comment by jckuester** [comment]
Hi @MorganGeek :wave:

you don't have to use environment variables, you can also use the profile flag, i.e., `awsls -profile myprofile ...` to pick a profile from  `~/.aws/credentials`. However, picking the up the region for a profile from `~/.aws/config` doesn't work right now (a bug). So you might want to use, for instance, `awsls -profile myprofile -region us-west-2 ...`. Does this help?

**Comment by jckuester** [comment]
Hi @briandunbar,

$ ./bin/awsls -profile myprofile -region us-east-01 aws_vpc

> Error:️ failed to initialize Terraform AWS provider: failed to configure provider (name=aws, version=2.59.0): Invalid AWS Region: us-east-01

In this case, `us-east-01` is not a valid region and `awsls` should work with `us-east-1`.

> bdunbar@hilda:~
> $ ./bin/awsls -profile myprofile aws_vpc

I guess, `awsls` is correctly using your profile `myprofile` here, but is not picking up the region from `~/.aws/config` for that profile (a bug). Is that what you would expect?

> bdunbar@hilda:~
> $ ./bin/awsls aws_vpc

I guess, `awsls` is correctly using your `default` profile here, but again, is not picking up the region from `~/.aws/config` for the default profile (a bug). Is that what you would expect?

**Comment by MorganGeek** [comment]
> Hi @MorganGeek 👋
> 
> you don't have to use environment variables, you can also use the profile flag, i.e., `awsls -profile myprofile ...` to pick a profile from `~/.aws/credentials`. However, picking the up the region for a profile from `~/.aws/config` doesn't work right now (a bug). So you might want to use, for instance, `awsls -profile myprofile -region us-west-2 ...`. Does this help?

Thank you @jckuester , in fact it might work indeed :) 
I'm facing another issue now (but I'll check if it was already faced by anyone else, otherwise I'll open a new one), thanks !

**Comment by jckuester** [comment]
Hi all,

thanks for your valuable feedback. In [v0.3.0](https://github.com/jckuester/awsls/releases/tag/v0.3.0), I fixed some buggy experience:

* The region configured in `~/.aws/config` is now being picked up correctly for your AWS profile
* Region flags don't need come first anymore, `awsls aws_instace -region us-west-2` is possible too (cc @nyamaste)
* POSIX compatible experience for arguments, e.g.., `-a` works as shorthand flag for `--attributes`, `-r` for `--region`, and `-p` for `--profile`
