### ISSUE TITLE
AWS SSM Parameters

### ISSUE THREAD

**Issue by klauern** [jckuester/awsls#6]
I am not sure how to generate or test generation of AWS SSM Parameters and Parameter groups.  It would be nice to have that, as SSM Parameters are often used to store configuration and secrets, so knowing what parameters were defined in accounts would be useful.

**Comment by jckuester** [comment]
Hi @klauern :wave: 

Thanks for opening the issue. My generator can currently not automatically generate list code for the [`aws_ssm_parameter`](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html) resource, but I'll adapt the generator accordingly. I'll come back to you once I am done.

I cannot find any resources called `Parameter groups`, can you point me to some documentation or the API about what resource you exactly mean? Thanks.

**Comment by klauern** [comment]
Hello @jckuester, 

I'm not sure if Parameter groups is a thing.  I'm probably just thinking of what we refer to them when working with a number of them under a given path, so you can disregard that specific request.

Thank you for looking into it.  I'm not sure how the Terraform Module works with multiple parameters, so it might not be possible to list all of them for all I know.  I'm curious what you discover when you start working on it, though.

**Comment by jckuester** [comment]
I have added SSM parameters is release [v0.2.0](https://github.com/jckuester/awsls/releases/tag/v0.2.0). You can list ssm parameters with 

```
$ awsls [your region/profile flags] aws_ssm_parameter

TYPE                ID                                      REGION      CREATED   
aws_ssm_parameter   /foo/bar/parameter                      us-west-2   N/A       
```

I guess the groups/paths you are were mentioning are part of the ID, i.e., in the example above `/foo/bar`.

All valid attributes can be found [here](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html#argument-reference). For example, you could list the value of parameters with

```
$ awsls [your region/profile flags] -attributes value aws_ssm_parameter
```

Hope I could help!

**Comment by klauern** [comment]
That's great!  I'll try to take a look at this sometime this week.  I appreciate the response.
